import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Dropdown from "@/components/Dropdown";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Crombie Next",
  description: "Generated by create next app",
};

const categoryArray = [{ name: 'women' }, { name: 'men' }, { name: 'kids' }, { name: 'outlet' }]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        

        
        {/* <div className="flex gap-6 justify-center font-bold text-fuchsia-400">
          <Link href="/" className="hover:text-fuchsia-600">Home</Link>
          <Link href="/categorias/zapatos" className="hover:text-fuchsia-600">Zapatos</Link>
        </div> */}
        
        <div className="flex items-center justify-center ">


          <ul className="flex gap-6 justify-center font-bold text-fuchsia-400 ">
            <Link href="/">Home</Link>
            <Link href="/login">Login</Link>

            {categoryArray.map((category) => (<Link href={`/categorias/${category.name}`}>{category.name}</Link>))}

            

          </ul>

          <div className="fixed right-3 top-4">

            <Dropdown/>
          </div>

        </div>
        {children}
      </body>
    </html>
  );
}
