export type ProductType = {
  id: number;
  nombre: string;
  precio: number;
  imagen: string;
  categoria: string;
  tallas?: string[] | number[] | null;
  enStock: boolean;
  descripcion: string;
};
export const productos = [
  {
    id: 1,
    nombre: "Camisa Azul Casual",
    precio: 29.99,
    imagen: "/images/camisa-azul.jpg",
    categoria: "Ropa",
    tallas: ["S", "M", "L", "XL"],
    enStock: true,
    descripcion: "Camisa azul de algodón, ideal para uso casual.",
  },
  {
    id: 2,
    nombre: "Pantalón de Mezclilla",
    precio: 39.99,
    imagen: "/images/pantalon-mezclilla.jpg",
    categoria: "Ropa",
    tallas: ["S", "M", "L"],
    enStock: true,
    descripcion: "Pantalón de mezclilla resistente, perfecto para el día a día.",
  },
  {
    id: 3,
    nombre: "Sudadera Negra con Capucha",
    precio: 49.99,
    imagen: "/images/sudadera-negra.jpg",
    categoria: "Ropa",
    tallas: ["M", "L", "XL"],
    enStock: true,
    descripcion: "Sudadera cómoda y cálida con diseño minimalista.",
  },
  {
    id: 4,
    nombre: "Zapatillas Deportivas Blancas",
    precio: 59.99,
    imagen: "/images/zapatillas-blancas.jpg",
    categoria: "Calzado",
    tallas: [38, 39, 40, 41, 42, 43],
    enStock: false,
    descripcion: "Zapatillas deportivas ligeras y cómodas.",
  },
  {
    id: 5,
    nombre: "Camiseta Blanca Básica",
    precio: 19.99,
    imagen: "/images/camiseta-blanca.jpg",
    categoria: "Ropa",
    tallas: ["S", "M", "L", "XL"],
    enStock: true,
    descripcion: "Camiseta blanca de algodón, imprescindible en tu armario.",
  },
  {
    id: 6,
    nombre: "Chaqueta de Cuero",
    precio: 89.99,
    imagen: "/images/chaqueta-cuero.jpg",
    categoria: "Ropa",
    tallas: ["M", "L"],
    enStock: true,
    descripcion: "Chaqueta de cuero auténtico con diseño elegante.",
  },
  {
    id: 7,
    nombre: "Botas de Montaña",
    precio: 74.99,
    imagen: "/images/botas-montana.jpg",
    categoria: "Calzado",
    tallas: [40, 41, 42, 43],
    enStock: true,
    descripcion: "Botas impermeables, ideales para senderismo.",
  },
  {
    id: 8,
    nombre: "Vestido Floral",
    precio: 49.99,
    imagen: "/images/vestido-floral.jpg",
    categoria: "Ropa",
    tallas: ["S", "M", "L"],
    enStock: true,
    descripcion: "Vestido veraniego con estampado floral.",
  },
  {
    id: 9,
    nombre: "Abrigo de Lana",
    precio: 129.99,
    imagen: "/images/abrigo-lana.jpg",
    categoria: "Ropa",
    tallas: ["M", "L", "XL"],
    enStock: true,
    descripcion: "Abrigo cálido de lana, perfecto para el invierno.",
  },
  {
    id: 10,
    nombre: "Pantalón Chino Beige",
    precio: 34.99,
    imagen: "/images/pantalon-chino.jpg",
    categoria: "Ropa",
    tallas: ["S", "M", "L"],
    enStock: true,
    descripcion: "Pantalón chino de corte clásico y elegante.",
  },
  {
    id: 11,
    nombre: "Falda Plisada Negra",
    precio: 39.99,
    imagen: "/images/falda-plisada.jpg",
    categoria: "Ropa",
    tallas: ["S", "M", "L"],
    enStock: true,
    descripcion: "Falda plisada versátil para cualquier ocasión.",
  },
  {
    id: 12,
    nombre: "Zapatos de Vestir",
    precio: 99.99,
    imagen: "/images/zapatos-vestir.jpg",
    categoria: "Calzado",
    tallas: [40, 41, 42, 43],
    enStock: true,
    descripcion: "Zapatos formales de cuero negro.",
  },
  {
    id: 13,
    nombre: "Guantes de Invierno",
    precio: 14.99,
    imagen: "/images/guantes.jpg",
    categoria: "Accesorios",
    tallas: ["S", "M", "L"],
    enStock: true,
    descripcion: "Guantes de lana para protegerte del frío.",
  },
  {
    id: 14,
    nombre: "Sombrero de Paja",
    precio: 24.99,
    imagen: "/images/sombrero.jpg",
    categoria: "Accesorios",
    tallas: ["Única"],
    enStock: true,
    descripcion: "Sombrero clásico para días soleados.",
  },
  {
    id: 15,
    nombre: "Chaleco de Plumas",
    precio: 59.99,
    imagen: "/images/chaleco-plumas.jpg",
    categoria: "Ropa",
    tallas: ["M", "L"],
    enStock: true,
    descripcion: "Chaleco ligero y abrigado, ideal para el entretiempo.",
  },
  {
    id: 16,
    nombre: "Mochila Deportiva",
    precio: 49.99,
    imagen: "/images/mochila.jpg",
    categoria: "Accesorios",
    enStock: true,
    descripcion: "Mochila resistente con compartimentos múltiples.",
  },
  {
    id: 17,
    nombre: "Cinturón de Cuero",
    precio: 19.99,
    imagen: "/images/cinturon.jpg",
    categoria: "Accesorios",
    tallas: ["S", "M", "L"],
    enStock: true,
    descripcion: "Cinturón clásico en cuero negro.",
  },
  {
    id: 18,
    nombre: "Sandalias Veraniegas",
    precio: 29.99,
    imagen: "/images/sandalias.jpg",
    categoria: "Calzado",
    tallas: [38, 39, 40, 41],
    enStock: true,
    descripcion: "Sandalias cómodas para días calurosos.",
  },
  {
    id: 18,
    nombre: "Leggings Deportivos",
    precio: 24.99,
    imagen: "/images/leggings-deportivos.jpg",
    categoria: "Ropa",
    tallas: ["S", "M", "L", "XL"],
    enStock: true,
    descripcion: "Leggings elásticos y cómodos, ideales para entrenar.",
  },
  {
    id: 19,
    nombre: "Bufanda de Lana",
    precio: 19.99,
    imagen: "/images/bufanda-lana.jpg",
    categoria: "Accesorios",
    tallas: null,
    enStock: true,
    descripcion: "Bufanda cálida y suave para días fríos.",
  },
  {
    id: 20,
    nombre: "Sombrero de Paja",
    precio: 15.99,
    imagen: "/images/sombrero-paja.jpg",
    categoria: "Accesorios",
    tallas: ["Talla Única"],
    enStock: true,
    descripcion: "Sombrero ligero y fresco para proteger del sol.",
  },
  {
    id: 21,
    nombre: "Short Deportivo",
    precio: 29.99,
    imagen: "/images/short-deportivo.jpg",
    categoria: "Ropa",
    tallas: ["S", "M", "L"],
    enStock: true,
    descripcion: "Short transpirable perfecto para actividades deportivas.",
  },
  {
    id: 22,
    nombre: "Sandalias de Playa",
    precio: 19.99,
    imagen: "/images/sandalias-playa.jpg",
    categoria: "Calzado",
    tallas: [36, 37, 38, 39, 40, 41],
    enStock: true,
    descripcion: "Sandalias cómodas y ligeras para el verano.",
  },
  {
    id: 23,
    nombre: "Blusa de Encaje",
    precio: 34.99,
    imagen: "/images/blusa-encaje.jpg",
    categoria: "Ropa",
    tallas: ["S", "M", "L"],
    enStock: true,
    descripcion: "Blusa elegante con detalles de encaje.",
  },
  {
    id: 24,
    nombre: "Reloj Deportivo",
    precio: 59.99,
    imagen: "/images/reloj-deportivo.jpg",
    categoria: "Accesorios",
    tallas: null,
    enStock: true,
    descripcion: "Reloj resistente al agua con cronómetro integrado.",
  },
  {
    id: 25,
    nombre: "Parka Impermeable",
    precio: 89.99,
    imagen: "/images/parka-impermeable.jpg",
    categoria: "Ropa",
    tallas: ["M", "L", "XL"],
    enStock: true,
    descripcion: "Parka funcional para días lluviosos.",
  },
  {
    id: 26,
    nombre: "Cinturón de Cuero",
    precio: 25.99,
    imagen: "/images/cinturon-cuero.jpg",
    categoria: "Accesorios",
    tallas: ["S", "M", "L"],
    enStock: true,
    descripcion: "Cinturón clásico de cuero negro.",
  },
  {
    id: 27,
    nombre: "Chaleco de Punto",
    precio: 39.99,
    imagen: "/images/chaleco-punto.jpg",
    categoria: "Ropa",
    tallas: ["S", "M", "L", "XL"],
    enStock: true,
    descripcion: "Chaleco de punto suave y moderno.",
  },
  {
    id: 28,
    nombre: "Gorra Deportiva",
    precio: 14.99,
    imagen: "/images/gorra-deportiva.jpg",
    categoria: "Accesorios",
    tallas: ["Talla Única"],
    enStock: true,
    descripcion: "Gorra ligera con visera curva.",
  },
  {
    id: 29,
    nombre: "Mono Enterizo",
    precio: 59.99,
    imagen: "/images/mono-enterizo.jpg",
    categoria: "Ropa",
    tallas: ["S", "M", "L"],
    enStock: true,
    descripcion: "Mono casual y elegante con cinturón incluido.",
  },
  {
    id: 30,
    nombre: "Mochila Casual",
    precio: 49.99,
    imagen: "/images/mochila-casual.jpg",
    categoria: "Accesorios",
    tallas: null,
    enStock: true,
    descripcion: "Mochila resistente con múltiples compartimentos.",
  },

];
